### ISSUE TITLE
Build fails after `make clean` as unable to find openj9_version_info.h

### ISSUE THREAD

**Issue by groeges** [ibmruntimes/openj9-openjdk-jdk8#11]
When running a `make all` after a `make clean` the build fils with the error below. 
```
openj9_version.c:27:33: fatal error: openj9_version_info.h: No such file or directory
 #include "openj9_version_info.h"
                                 ^
compilation terminated.
../makelib/targets.mk:296: recipe for target 'openj9_version.o' failed
```
In order to get this to work the `bash configure` script needs to be run again. 
This should not be required and a `make all` should be able to be run after a `make clean`

**Comment by jdekonin** [comment]
This was reported in https://github.com/ibmruntimes/openj9-openjdk-jdk9/issues/11 and resolved in https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/46.

I expect the same changes would apply for this set of extensions.

**Comment by groeges** [comment]
@jdekonin Thanks. I did know it was found in JDK9 and was looking for the issue when you posted your comment. Thanks. I will apply that change to JDK8.

**Comment by groeges** [comment]
The PR for this issue is: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/13
