### ISSUE TITLE
Java 8 doesn't have fontconfig property files

### ISSUE THREAD

**Issue by JasonFengJ9** [ibmruntimes/openj9-openjdk-jdk8#111]
`Java 8 RI` has following `fontconfig` property files within `jre/lib`:
```
fontconfig.Turbo.properties.src
fontconfig.RedHat.5.bfc
fontconfig.RedHat.6.bfc
fontconfig.RedHat.5.properties.src
fontconfig.SuSE.10.bfc
fontconfig.RedHat.6.properties.src
fontconfig.SuSE.11.bfc
fontconfig.SuSE.10.properties.src
fontconfig.Turbo.bfc
fontconfig.bfc
fontconfig.SuSE.11.properties.src
fontconfig.properties.src
```
But `OpenJ9 Java 8` doesn't have these files, is this intentional?

related to: https://github.com/eclipse/openj9/issues/2659

Note: `Java 11 RI ea` doesn't have these files so far.

FYI: @DanHeidinga

**Comment by DanHeidinga** [comment]
@andrew-m-leonard Can you take a look at this?

**Comment by andrew-m-leonard** [comment]
OpenJDK  does not provide fontconfig for Linux, you need to install OS dependent libararies. OpenJDK does provide some for the following OS's:
```
aix.fontconfig.properties
bsd.fontconfig.properties
macosx.fontconfig.properties
solaris.fontconfig.properties
windows.fontconfig.properties
```
The RedHat, SuSe,... ones you mention above were ones we used to create/install in "old world" IBMJava, we don't use those any more.

See: https://docs.oracle.com/javase/7/docs/technotes/guides/2d/enhancements70.html#linuxfonts

So if specific fonts are required on Linux, the appropriate libfontconfig package should be installed.

**Comment by andrew-m-leonard** [comment]
So correct OpenJDK doesn't have these, by design.

**Comment by andrew-m-leonard** [comment]
This is as by OpenJDK design.
