### ISSUE TITLE
Add openssl to the third party licenses file

### ISSUE THREAD

**Issue by lumpfish** [ibmruntimes/openj9-openjdk-jdk8#119]
As a result of bundling openssl libraries with the jdk the openssl license needs to be added to the third party license notices file included in the built jdk.

**Comment by mstoodle** [comment]
I'm not sure I understand this one.... openj9-openjdk-jdk8 is not bundling an openssl library with its source code, so why is this license needed?

It's AdoptOpenJDK that will be doing the bundling, by specifying the appropriate configure options. How is this different than the font libraries or certificates that are also built into the OpenJDK binaries at AdoptOpenJDK? Those things aren't included in OpenJDK's license files are they?

I suppose we could provide it for "informational purposes" *in case* someone chooses to bundle the library.

**Comment by andrew-m-leonard** [comment]
@mstoodle true... I guess if someone builds their own binary using the --with-openssl... then they ought to be aware...

**Comment by andrew-m-leonard** [comment]
at the moment I am thinking of copying https://www.openssl.org/source/license.html to a new extensions licenses file, which then gets added to the built jdk...

**Comment by mstoodle** [comment]
ok, that doesn't sound unreasonable to me

**Comment by lumpfish** [comment]
Fixed by https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/121
