### ISSUE TITLE
openjdk_regression tests java/net/MulticastSocket fail due to timeouts on zLinux

### ISSUE THREAD

**Issue by andrew-m-leonard** [ibmruntimes/openj9-openjdk-jdk8#143]
The following tests fail for OpenJ9 on zLinux due to the test specified timeouts, between 1 and 5 seconds, most likely being too short for the environment:
- java/net/MulticastSocket/Promiscuous.java.Promiscuous
- java/net/MulticastSocket/SetLoopbackMode.java.SetLoopbackMode
- java/net/MulticastSocket/Test.java.Test
- java/nio/channels/DatagramChannel/MulticastSendReceiveTests.java
- java/nio/channels/DatagramChannel/Promiscuous.java

**Comment by ben-walsh** [comment]
I've just excluded these tests on JDK11 too.

What's the real fix here ? Should a OpenJDK contribution be made so that those testing on less powerful test machines aren't seeing false failures ?

**Comment by ben-walsh** [comment]
Further investigation determined that multicast networking is non-functional on the zLinux test machines - see https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/699

**Comment by andrew-m-leonard** [comment]
I concur this is an Adopt infra issue with their zLinux machine:
 https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/143
