### ISSUE TITLE
Add support for OpenSSL 1.0.x

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk8#187]
Currently the OpenSSL support is only for the 1.1.x version. Since most OSes don't provide this atm, to work around it the OpenJ9 0.11.0 release builds bundle the openssl 1.1 library. This is not ideal since the JVM will not pick up new openssl libraries when they are available. It may be desired to use updated openssl libraries to get bug fixes or security updates. If the openssl library is found on the OS, the user can install and update the library using standard package managers. This requires adding openssl support for 1.0

**Comment by pshipton** [comment]
@enasser @ashbm5

**Comment by groeges** [comment]
Completed. Closing.
