### ISSUE TITLE
OpenJ9 builds do not include jsig.lib on Windows

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk8#188]
The jsig.lib file should be included in the lib directory.

**Comment by keithc-ca** [comment]
Verified using https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jdk_x64_windows_openj9_8u202b08_openj9-0.12.1.zip
