### ISSUE TITLE
OpenJ9 builds do not put libjsig.so / jsig.dll in the correct places

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk8#189]
Windows:
bin\jsig.dll

Linux/AIX:
lib/libjsig.so

The jsig file does not need to be in the compressedrefs/default directory.

**Comment by keithc-ca** [comment]
Given that https://github.com/eclipse/openj9/issues/2100 has been closed, I expect the answer to this will be to back-port the makefile patterns used in Java 11+ which will mean none of the test artifacts will be included in a JRE or JDK image.

**Comment by keithc-ca** [comment]
Fixed in #211; verified via https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2019-03-14-16-57/OpenJDK8U-jdk_x64_windows_openj9_2019-03-14-16-57.zip
