### ISSUE TITLE
javadoc does not contain OpenJ9 extensions

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk8#20]
The javadoc created as part of the OpenJ9 build, found in `build/<platform>/docs`, does not contain the javadoc for OpenJ9 extensions:
 - Shared Classes, com.ibm.oti.shared
 - Management extensions, com.ibm.lang.management
 - gpu, com.ibm.gpu
 - Cuda4J, com.ibm.cuda
 - data access acceleration. com.ibm.dataaccess
 - JVM diagnostic utilities, com.ibm.jvm

See also eclipse/openj9#897

**Comment by pshipton** [comment]
I don't believe any of these were done. My understanding is that javadoc generation for Java 9 (and later I expect) doesn't work at all with OpenJ9.

**Comment by keithc-ca** [comment]
As noted in ibmruntimes/openj9-openjdk-jdk11#212, there are also files overridden by openj9 that contribute to javadoc: those should have the appropriate copyright notice in the html footer.
Perhaps the definitive definition of the list of overrides is the set of source files in preprocessed image of `openj9/jcl/src` (i.e. in `$(SUPPORT_OUTPUTDIR)/j9jcl_sources`).

**Comment by lumpfish** [comment]
Fixed by https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/342

**Comment by SueChaplain** [comment]
Does this completely fix https://github.com/eclipse/openj9/issues/897 please?

**Comment by lumpfish** [comment]
Yes, this also fixes https://github.com/eclipse/openj9/issues/897
