### ISSUE TITLE
Don't need jextract in bin

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk8#201]
#180 added jextract to the jre/bin directory, but I notice it's also in the bin directory. Since it's not a development tool, it doesn't need to be in the bin directory.

**Comment by pshipton** [comment]
@keithc-ca

**Comment by keithc-ca** [comment]
There's already a large number of executables in both directories (e.g. java, javaw, javaws, pack200, unpack200, etc.): is this a significant concern?

**Comment by pshipton** [comment]
Significant no. Just wrong.
