### ISSUE TITLE
javadoc contains unsupported extensions

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk8#21]
The javadoc created as part of the OpenJ9 build, found in `build/<platform>/docs`, contains extensions which are not supported on OpenJ9.
 - OpenJDK management extensions, com.sun.management

See also eclipse/openj9#898

**Comment by lumpfish** [comment]
Fixed by https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/342
