### ISSUE TITLE
AO8/J9 s390x builds do not work out of the box

### ISSUE THREAD

**Issue by sxa555** [ibmruntimes/openj9-openjdk-jdk8#23]
I presume this is somewhere around the `redirector.c` code within `openj9`

if you download the s390x AO8/J9 builds from www.AdoptOpenJDK.net and try to run it you get this error:

```
jcktest@csz25074:/dev/shm/jdk8u152-b16/bin$ ./java -version
Error: missing `server' JVM at `/dev/shm/jdk8u152-b16/jre/lib/s390x/server/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
jcktest@csz25074:/dev/shm/jdk8u152-b16/bin$ 
```
Creating a symbolic link from `jre/lib/s390x/server` to `jre/lib/s390x/j9vm` allows the JVM to start up, so somewhere along the lines in the build it's still looking for `libjvm.so` in HotSpot's location.

**Comment by pshipton** [comment]
Its caused by the jvm.cfg file, which needs to contain

```
-j9vm KNOWN
-server IGNORE
```

**Comment by sxa555** [comment]
The one in `jdk/src/solaris/bin/s390x` looks correct, but that isn't the one that's in the final distribution

**Comment by sxa555** [comment]
I think this is because default (non-OpenJ9) build on `s390x` is `zero` not `server`, which means `JVMCFG_ARCH` in `CopyFiles.gmk` ends up as `zero` instead of `s390x` so it doesn't copy the correct file. @pshipton I'm not sure where the fix for this needs to be. I'm happy to do it, but want it in the "correct" repo wherever that is.

**Comment by pshipton** [comment]
Strangely when we do builds they don't have the same issue, it picks up a jvm.cfg with `-j9vm KNOWN` and the build runs. We don't seem to be doing any special i.e. `bash ./configure --with-boot-jdk=/sdk/openjdk7/linux_390-64_cmprssptrs --enable-cuda --with-freemarker-jar=/tools/freemarker-2.3.8/lib/freemarker.jar && make images`. 

We don't want to have modifications to OpenJDK so modifying `jdk/make/CopyFiles.gmk` is not ideal, unless the modifications can be contributed to OpenJDK.

**Comment by sxa555** [comment]
Agreed - so my PR does what we've done for the other platforms -modify the jvm.cfg that is copied so that it copies the "correct" one that the build system is trying to pick up. Of course it might be sensible to delete the `s390x` on to avoid confusion, but if it works in some environments that may not be the sensible solution.

Is it definitely working for you on openjdk8 (as opposed to openjdk9?)

**Comment by pshipton** [comment]
> Is it definitely working for you on openjdk8 (as opposed to openjdk9?)

Yes.

```
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-openj9_2018_01_10_03_06-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux s390x-64 Compressed References 20180110_375557 (JIT enabled, AOT enabled)
OpenJ9   - f1ccd6b
OMR      - 7a770d6
OpenJDK  - 00e69f9 based on Java8_SR5_FP7_20171215_1234_B373586)

```

**Comment by pshipton** [comment]
Note `OpenJDK  - 00e69f9 based on Java8_SR5_FP7_20171215_1234_B373586` is a bug, see #22

**Comment by DanHeidinga** [comment]
> JVMCFG_ARCH in CopyFiles.gmk ends up as zero instead of s390x

Is there a way to control the default such that our existing changes to the `closed/` directory can ensure the OpenJ9 build uses `s390x`?

**Comment by sxa555** [comment]
I'm not sure there's an easy way without modifying the common files in the AdoptOpenJDK repositories, but if you know of one (I'm not an expert in the openjdk build system) that would likely be preferable. If JVM_VARIANTS can be overridden to have SERVER in there then that would presumably work (although I can't comment on side effects of that approach ...)

**Comment by sxa555** [comment]
OK so `makejdk-any-platform.sh` in the `openjdk-build` repo is what sets `JVM_VARIANT` to `zero` on `s390x`.

Although if I'm reading the logic corrently it should set `JVM_VARIANT=server` when `BUILD_VARIANT=openj9` (Set via the `--variant openj9` parameter which we're passing to `makejdk-any-platform.sh`

**Comment by sxa555** [comment]
OK I believe the PR I've just submitted to openjdk-build will resolve this in a more satisfactory way assuming it doesn't have any side effects.

**Comment by sxa555** [comment]
Merged and I've kicked off a new bulid so hopefully we'll have a good nightly build available in the next couple of hours

**Comment by sxa555** [comment]
Fixed in https://github.com/AdoptOpenJDK/openjdk8-openj9-nightly/releases/download/jdk8u152-b16-20181001/OpenJDK8-OPENJ9_s390x_Linux_20181001.tar.gz and later builds. Closing
