### ISSUE TITLE
fix OPENJDK_TAG in java version output

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk8#27]
Java version output of openJ9 builds doesn't contain proper OPENJDK_TAG.

> openjdk version "1.8.0-internal"
> OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2018_01_09_13_02-b00)
> Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180109_42 (JIT enabled, AOT enabled)
> OpenJ9   - b116fb3
> OMR      - 7a770d6
> OpenJDK  - 00e69f9 based on )

Proper output

> openjdk version "1.8.0-internal"
> OpenJDK Runtime Environment (build 1.8.0-internal-bhamaram_2018_01_10_00_29-b00)
> Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180110_000000 (JIT enabled, AOT enabled)
> OpenJ9   - b116fb3
> OMR      - 7a770d6
> OpenJDK  - 00e69f9 based on jdk8u152-b16)

**Comment by mbvreddy** [comment]
Version output of latest openjdk8-openj9 build is 

openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2018_01_26_13_02-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180126_55 (JIT enabled, AOT enabled)
OpenJ9   - 5d59436
OMR      - ec2c3bf
OpenJDK  - ac9998c based on **jdk8u152-b16**)
