### ISSUE TITLE
JDK8 fails to build on Gentoo

### ISSUE THREAD

**Issue by liketechnik** [ibmruntimes/openj9-openjdk-jdk8#291]
Build Log: https://gitlab.com/snippets/1851154
I've successfully compiled the 'normal' openjdk8 on this machine, but openj9 fails for some reason.
I'm happy to provide any additional info you need.

**Comment by DanHeidinga** [comment]
I took a look at the build log and the errors indicate libdwarf is missing.  Have you confirmed that the prereqs have been installed? See the docker files for a list of the required packages:
https://github.com/eclipse/openj9/blob/e7e58dd59a2a239d9105e1e93f2545f88d347451/buildenv/docker/jdk8/x86_64/ubuntu16/Dockerfile#L50-L51

**Comment by liketechnik** [comment]
Yes, that's right. Sorry for the oversight on my side. The problem is, that Gentoo doesn't have a package for dwarf. I have a 'dwarf.h' header in /usr/include , but the build expects libdwarf.h to be available. I'm not sure if I could just symlink libdwarf.h to dwarf.h or if I'm missing something here.

**Comment by pshipton** [comment]
> I'm not sure if I could just symlink libdwarf.h to dwarf.h or if I'm missing something here.

Could try it and see what happens. libdwarf is used for creating and reading diagnostics, if there is a problem in that area it won't affect running the JVM.

**Comment by liketechnik** [comment]
Gonna try it out in the following days and report back here.

**Comment by superwhiskers** [comment]
hi. i've assembled an ebuild here in my portage overlay that also contains a libdwarf ebuild
https://github.com/superwhiskers/nya/tree/master/dev-java/openj9-openjdk-jdk8

**Comment by keithc-ca** [comment]
A symlink is unlikely to work. On my system `dwarf.h` and `libdwarf.h` are very different:
```
$ ls -l /usr/include/libdwarf
total 236
-rw-r--r-- 1 root root  70048 Feb 10  2018 dwarf.h
-rw-r--r-- 1 root root 166991 Feb 17  2018 libdwarf.h
```

**Comment by liketechnik** [comment]
To be honest I kinda lost track of this after not getting it to work. I'm really happy that @superwhiskers has a working ebuild now.

Because it seems to be no problem building it when (lib)dwarf is correclty installed I'll go ahead and finally close this issue.

**Comment by liketechnik** [comment]
P. S.: Most importantly, thanks to the other commenters for their helpful input.
