### ISSUE TITLE
jdmpview help refers to dtfjview

### ISSUE THREAD

**Issue by smithwil** [ibmruntimes/openj9-openjdk-jdk8#314]
In the AdoptOpenJDK with OpenJ9 Java 8 JDKs, running `jdmpview -help` prints text that calls the tool `dtfjview` and includes some example commands for running `dtfjview`. The executable in the JDK is named `jdmpview` so the help text should use that name to avoid confusion.

**Comment by doveye** [comment]
FYI, this is the output I get for the jdmpview usage help on a Linux installation (Java 8 with OpenJ9 0.14.2 from AdoptOpenJDK):

> Usage: "dtfjview -core <core_file> [-verbose]" or 
>        "dtfjview -zip <zip_file> [-verbose]" or 
>        "dtfjview -version"
> 
> To analyze dumps from DDR-enabled JVMs, dtfjview only requires a core file.
> 
> The default ImageFactory is null. To change the ImageFactory use: 
> 	 -J-Dcom.ibm.dtfj.image.factoryclass=<classname> 
> 
> dtfjview can also be used in 'batch mode' whereby commands can be issued without entering an interactive prompt.
> This processing is controlled via the following command line options :
>         -cmdfile <path to command file> : will read and sequentially execute
>                                           a series of dtfjview commands in the specified file
>         -charset <character set name>   : specifies the character set for the commands in -cmdfile.
>         -outfile <path to output file>  : file to store any output generated by commands
>         -overwrite                      : specifies that the file specified by -outfile should be overwritten
>         -append                         : specifies that the file specified by -outfile should be appended.
> 
> It is possible to execute a single command without specifying a command file by appending the command to the end  of the command line which executes dtfjview
> e.g. dtfjview -core mycore.dmp info class
> 
> Finally, some commands which take the * parameter will need to have that specified on the command line as ALL
> This is to ensure correct processing by the OS e.g. dtfjview -core mycore.dmp info thread ALL
