### ISSUE TITLE
Create openj9-0.15.0 branch

### ISSUE THREAD

**Issue by lumpfish** [ibmruntimes/openj9-openjdk-jdk8#320]
The eclipse/openj9 and eclipse/openj9-omr openj9-0.15.0-m1 milestone tags have been created.
An openj9-0.15.0 branch needs to be created in this repository to build the correct levels of openj9 and openjdk for the jdk8 July quarterly update.
The most recent jdk8 openj9 acceptance testing job https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK8-Acceptance/15/ successfully merged openj9-staging into openj9 following a successful build + test run.

@pshipton - please can you confirm:
1. That the latest level of the openj9 branch is what the openj9-0.15.0 branch should be created from?
2. That J9JDK_EXT_VERSION should be 8.0.222.0-m1

**Comment by pshipton** [comment]
@lumpfish confirmed.

**Comment by lumpfish** [comment]
Branch openj9-0.15.0 created.
Also regenerated the autoconf files.
