### ISSUE TITLE
Build Windows with .pdb files

### ISSUE THREAD

**Issue by dsouzai** [ibmruntimes/openj9-openjdk-jdk8#373]
We need to have the option to build OpenJ9 on Windows with .pdb files. Every time we see an issue on Windows, we're told that we can just build Windows and then grab the .pdb files. It is *extremely* non-trivial to build on Windows, at least in my experience.

We should have the means to optionally copy over the .pdb files (that are generated anyway when we compile OpenJ9) over to the `j2sdk_image` / `j2re_image` dirs; the build job can then be modified to add the appropriate Makefile option. Either that or the build job should have the means to zip up and upload to artifactory the .pdb files. @AdamBrousseau do you have an opinion on which option is better?

**Comment by keithc-ca** [comment]
Building on Windows isn't significantly different than other platforms in my experience.

However, I am actively working to unify OMR and OpenJ9 with the way that openjdk handles debug information so that one (or a build) can configure with `--with-native-debug-symbols=external` or `--with-native-debug-symbols=zipped`; then the resulting files (`.pdb` on Windows, `.debuginfo` or `.diz` on Linux) can be packaged up and made available alongside a build.

**Comment by keithc-ca** [comment]
I've opened the following pull requests as the first step towards making debug information available:
* https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/380
* https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/270
* https://github.com/ibmruntimes/openj9-openjdk-jdk14/pull/17
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/174

They add a new make target: `debug-image` (which is a prerequisite of `all` - the goal of most builds).
That target copies all the debug information files (`.diz` when zipped, `.dSYM` on MacOSC, `.pdb` on Windows and `.debuginfo` on other platforms) and places it within `images/debug-info`. Copying the contents (recursively) of `debug-image` into the jdk directory (jre for Java 8) should result in a package with the right information to support the appropriate debugger.

For the moment, debug information will only be collected for openjdk artifacts. Future pull requests will make openj9 and omr follow the (naming) conventions established by openjdk so their debugging information will also be included in the debug image.

Changes to builds via jenkins or at adoptopenjdk.net will be required to make archives of the debug information available for those builds.

**Comment by keithc-ca** [comment]
https://github.com/eclipse/openj9/pull/8691 will make an archive of debug information available from jenkins builds.

**Comment by keithc-ca** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/pull/1597 will capture debug information archives for builds made available at https://adoptopenjdk.net.

**Comment by keithc-ca** [comment]
I believe this is complete.
