### ISSUE TITLE
JVM crashed with our application inside docker container

### ISSUE THREAD

**Issue by yangzhang-ibm-au** [ibmruntimes/openj9-openjdk-jdk8#378]
Hi,

We are an IBM internal team, we have been seeing a JVM crash with a "Segmentation error" while running one of our applications inside a docker container with the latest stable release of the OpenJ9 (1.8.0_242). The application itself does not log any error to stdout, the JVM simply crashes. (please check the attached stderr logs).

This happened for multiple times when we triggered a series of ElasticSearch index refresh actions in our application, but there wasn't a clear pattern when it happens, it's not consistently happening.

We suspect this is a bug in the OpenJ9 implementation of the JDK as we have tested the same scenario of same application with "**hotspot**" implementation in our docker image and cannot reproduce the crash.

**Below are more details:**

**Java version info:**
```
# java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191017_442 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)
```

**Runtime Environment:**
Docker containers with Ubuntu 16.04.6 LTS (Xenial Xerus) image, managed by Mesos + Marathon, running on Ubuntu 16.04.6 LTS dedicated VMs on IBM Cloud.

The attached stderr info was from an earlier occurrence of the issue, it might not contain enough info for troubleshooting. As suggested by folks in **java-at-ibm** Slack channel, we followed the Mustgather guide https://www.ibm.com/support/pages/node/344411 and got the java core dump, snap trace, etc via further tests. We can provide these files and part of the stdout of our application via a separate email to the assignee of this issue. 

Btw, we firstly raised this in **java-at-ibm** Slack channel and then was routed to creating a Salesforce case, and finally we were told that it's better to raise an issue here in Github, and @jerrylui803 might be able to help as suggested by IBM Support team. We appreciate the help from anyone works in this area or who has met the similar issue before. Thanks!
[](url)
Yang

**Comment by yangzhang-ibm-au** [comment]
**stderr info:**

```
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007FB2491A2710 Handler2=00007FB248A87E80 InaccessibleAddress=0000000000000000
RDI=00007FB21C028E40 RSI=0000000755BF86C5 RAX=00007FB213F710C0 RBX=00007FB21C028E40
RCX=0000000000000050 RDX=0000000755BF8870 R8=0000000000000050 R9=0000000000000050
R10=0000000002631688 R11=00007FB225B63210 R12=0000000000000000 R13=00007FB22400283C
R14=0000000755BF8870 R15=0000000755BF86C5
RIP=0000000000000000 GS=0000 FS=0000 RSP=00007FB224002778
EFlags=0000000000010246 CS=0033 RBP=00007FB22400283C ERR=0000000000000014
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000000
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm2 9268d30e0eb0cb3f (f: 246467392.000000, d: -5.494049e-220)
xmm3 e8d0b5910aa77679 (f: 178747008.000000, d: -7.806457e+196)
xmm4 11b8f9eda0d29930 (f: 2698156288.000000, d: 2.699051e-223)
xmm5 abbaf804ae675d4b (f: 2926009600.000000, d: -4.932004e-98)
xmm6 d0e91942b8da06fc (f: 3101296384.000000, d: -5.951955e+81)
xmm7 eb5ae7d55107b208 (f: 1359458816.000000, d: -1.382101e+209)
xmm8 71df3366f3c07d28 (f: 4089478400.000000, d: 3.250739e+240)
xmm9 0000000000000006 (f: 6.000000, d: 2.964394e-323)
xmm10 4b2657808bdeacf4 (f: 2346626304.000000, d: 1.069960e+54)
xmm11 c4d4f46def1b08e6 (f: 4011526400.000000, d: -3.958250e+23)
xmm12 bcd6e00000000000 (f: 0.000000, d: -1.269818e-15)
xmm13 bfa01346f6ef8000 (f: 4142891008.000000, d: -3.139707e-02)
xmm14 40357cd0e7026640 (f: 3875694080.000000, d: 2.148756e+01)
xmm15 3c330a683871ff68 (f: 946995072.000000, d: 1.032196e-18)
Target=2_90_20191017_442 (Linux 4.4.0-171-generic)
CPU=amd64 (8 logical CPUs) (0x7daada000 RAM)
----------- Stack Backtrace -----------
(0x00007FB248AB6062 [libj9prt29.so+0x4e062])
(0x00007FB248A88BE3 [libj9prt29.so+0x20be3])
(0x00007FB248AB60DE [libj9prt29.so+0x4e0de])
(0x00007FB248AB61D4 [libj9prt29.so+0x4e1d4])
(0x00007FB248A88BE3 [libj9prt29.so+0x20be3])
(0x00007FB248AB5F3B [libj9prt29.so+0x4df3b])
(0x00007FB2491A2214 [libj9vm29.so+0x9f214])
(0x00007FB248A88BE3 [libj9prt29.so+0x20be3])
(0x00007FB2491A2485 [libj9vm29.so+0x9f485])
(0x00007FB248A880AA [libj9prt29.so+0x200aa])
(0x00007FB24AE18390 [libpthread.so.0+0x11390])
---------------------------------------
```

**Comment by JasonFengJ9** [comment]
Note that this is OpenJ9 extension repo for Java 8 which contains OpenJDK JCL and some glue code for OpenJ9 JVM.
The crash occurred in JVM, https://github.com/eclipse/openj9/issues is the preferred place to open such an issue instead.

The JVM version in question is `20191017_442`, does it happen to a newer release version `jdk8u242-b08_openj9-0.18.1`  or latest nightly builds?

**Comment by yangzhang-ibm-au** [comment]
@JasonFengJ9  Thanks for the info! We haven't tested other versions of OpenJ9 JVM yet, do you think it's worth a try?

**Comment by yangzhang-ibm-au** [comment]
We just reproduced the issue with jdk8u242-b08_openj9-0.18.1 (OpenJDK build 1.8.0_242-b08). I will open a new issue in https://github.com/eclipse/openj9/issues.

**Comment by yangzhang-ibm-au** [comment]
Created this issue: https://github.com/eclipse/openj9/issues/8636
