### ISSUE TITLE
xLinux builds of openjdk8-openj9 are failing

### ISSUE THREAD

**Issue by sxa555** [ibmruntimes/openj9-openjdk-jdk8#44]
Failures started on the 6th Feb build. Other platforms appear ok

```
../makelib/targets.mk:301: recipe for target 'jswalk.o' failed
makefile:491: recipe for target 'j9codert_vm' failed
OpenJ9.gmk:291: recipe for target 'build-j9' failed
/mnt/home/jenkins/workspace/openjdk8_openj9_build_x86-64_linux/openjdk/closed/make/Main.gmk:31: recipe for target 'j9vm-build' failed: integer expression expected
```

**Comment by ben-walsh** [comment]
I've opened https://github.com/eclipse/openj9/issues/1180 to cover.

**Comment by sxa555** [comment]
I have temporarily replaced the following symlinks on `bulid-joyent-ubuntu1604-x64-2` ONLY which appears to have resolved the problem since setting the `CC`/`CXX` variables before the build was run did not pick up the `-4.8` variants in all cases:
```
root@build-joyent-ubuntu1604-x64-2:/usr/bin# ln -sf g++-4.8 g++
root@build-joyent-ubuntu1604-x64-2:/usr/bin# ln -sf gcc-4.8 gcc
root@build-joyent-ubuntu1604-x64-2:/usr/bin# ln -sf gcc-ar-4.8 gcc-ar
root@build-joyent-ubuntu1604-x64-2:/usr/bin# ln -sf gcc-nm-4.8 gcc-nm
root@build-joyent-ubuntu1604-x64-2:/usr/bin# ln -sf gcc-ranlib-4.8 gcc-ranlib
root@build-joyent-ubuntu1604-x64-2:/usr/bin# ln -s gcc-ranlib-5 gcc-ranlib
```
Pleas no-one close this issue until we have reverted these changes and either

(1) ansible playbooks are modified to handle this (I believe the presence of `gcc` and `g++` standalone as well as the `-4.8` variants has likely caused this - the v5 packages were installed around the time this started failing) https://github.com/AdoptOpenJDK/openjdk-infrastructure/blame/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml

(2) the openj9 builds are modified to be able to accept the CC/CXX environment variables properly to allow it to be overridden in all of the build configure steps (Currently the top level one picks it up but the OMR and possibly others don't - leading to this problem.

It's also worth pointing out that we are currenty building with gcc 5.4.0 on s390x and 6.3.1 on ppc64le, and now we will be forcing x64 to 4.8 - so on the three architectures we're currently using three different gcc versions which I suspect isn't ideal.

**Comment by sxa555** [comment]
Seems that in trying to switch to using /usr/bin/gcc-4.8 the other platforms have now broken in the configure step (Possibly as a side effect of https://github.com/AdoptOpenJDK/openjdk-build/pull/228 but it's not immediately obvious why that would cause this failure)

https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_ppc64le_linux/82/console
https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_s390x_linux/77/console

**Comment by andrew-m-leonard** [comment]
Presume fixed...
