### ISSUE TITLE
Add shenandoah for better performance...

### ISSUE THREAD

**Issue by Malaska678** [ibmruntimes/openj9-openjdk-jdk8#450]

**Comment by pshipton** [comment]
This project supports OpenJ9. For OpenJ9 see the metronome gc policy: `-Xgcpolicy:metronome` is designed for applications that require precise response times. Garbage collection occurs in small interruptible steps to avoid stop-the-world pauses. This policy is available only on x86 Linux and AIX platforms.
https://www.eclipse.org/openj9/docs/gc/#metronome-policy

@dmitripivkine fyi
