### ISSUE TITLE
Number of cpus on AIX isn't determined correctly

### ISSUE THREAD

**Issue by jdekonin** [ibmruntimes/openj9-openjdk-jdk8#57]
If smt is enabled the correct number of processors is not correct on configure.

There are a number of ways that can be used to determine actual number of processors, I found this works for me on the systems I have access to, smt enabled or not at time of configure

```--with-jobs='pmcycles -m | wc -l | awk '{print $1}''```

**Comment by keithc-ca** [comment]
We might also factor in the SMT setting; it might make sense to use jobs=16 (as if smt=2) on a system like this:
```
$ lparstat
System configuration: type=Shared mode=Uncapped smt=4 lcpu=32 mem=65536MB psize=20 ent=0.80
```

**Comment by andrew-m-leonard** [comment]
This should be turned into an openjdk_contribution issue.

**Comment by groeges** [comment]
@andrew-m-leonard Think this was contributed. Can we close this issue?

**Comment by groeges** [comment]
Andrew Leonard stated in issue: https://github.com/ibmruntimes/openj9-openjdk-jdk11/issues/17  that `this has been contributed to openjdk (jdk13), but not backported.
We could try and request a backport, but I suspect they may not consider it a significant issue to backport`, so this is not currently available in jdk8.

**Comment by andrew-m-leonard** [comment]
This has now been backported to jdk8u-dev, will appear in next jdk8u build.
