### ISSUE TITLE
Does OpenJDK 8 + OpenJ9 support JDK 14's ShowCodeDetailsInExceptionMessages parameter？

### ISSUE THREAD

**Issue by lin-wang-rabbit** [ibmruntimes/openj9-openjdk-jdk8#736]
I tried directly setting -XX:+ShowCodeDetailsInExceptionMessages when running OpenJDK 8 + OpenJ9, but it seems to not have any effect. The NPE messages still don't contain code details. here is version info :
```shell
/Library/Java/JavaVirtualMachines/ibm-semeru-open-8.jdk/Contents/Home/bin/java -version
openjdk version "1.8.0_402"
IBM Semeru Runtime Open Edition (build 1.8.0_402-b06)
Eclipse OpenJ9 VM (build openj9-0.43.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20240131_892 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 0fa9d9c532 based on jdk8u402-b06)

```
  
  JDK 14 introduced the -XX:+ShowCodeDetailsInExceptionMessages parameter to show code details in exception messages. This can help locate the root cause of NPEs faster. 
  
  I'd like to confirm whether OpenJDK 8 + OpenJ9 supports this parameter? 
  If not, can support be considered in a future release? If support cannot be added in the short term, is there a workaround that can achieve similar effects?
  his parameter is very helpful for quickly debugging issues. Hope it can be supported as soon as possible, thanks!

**Comment by JasonFengJ9** [comment]
`-XX:+ShowCodeDetailsInExceptionMessages` is part of [JEP 358: Helpful NullPointerExceptions](https://openjdk.org/jeps/358) which was a feature introduced since Java 14 as you noted.

It is possible to port this feature to earlier streams though no promise for the timeline.

**Comment by pshipton** [comment]
Seems to me that JCL changes are required to support the feature, Jason do you recall? I don't expect we would backport this feature to jdk8. Better to move from jdk8 to a newer version that supports the option.

**Comment by JasonFengJ9** [comment]
> Seems to me that JCL changes are required to support the feature, Jason do you recall?

Correct, it is the JCL changes required, iirc, there is no Java level restriction on natives.
There were thoughts about porting this feature to Java 8/11, just wasn't sure if it is necessary, I will give it a quick try for the next release (not 0.44).

**Comment by JasonFengJ9** [comment]
The proposal to backport [JEP 358: Helpful NullPointerExceptions](https://openjdk.org/jeps/358) was rejected because
we don't want to introduce changes like this that create differences between OpenJ9 and the Java 11/Java 8 RIs without a strong pro argument - some significant benefit to offset the potential issues the difference can cause (ie some customer has a programmatic dependency on how the current NPE messages are reported)

@lin-wang-rabbit if you have a compelling case to make, please reopen.
