### ISSUE TITLE
Refresh repo from upstream

### ISSUE THREAD

**Issue by AdamBrousseau** [ibmruntimes/openj9-openjdk-jdk8#78]
There is a recent change for Windows that is blocking us from adding Windows JDK8 builds at https://ci.eclipse.org/openj9/
Please update the openj9 branch with the new new changes

Link to the change: http://hg.openjdk.java.net/jdk8u/jdk8u/rev/a05ed58d5ae0
```
author | kevinw
-- | --
Sat, 07 Apr 2018 03:28:39 -0700 (3 weeks ago)
cddffb220808
2209644bcac4
common/autoconf/basics_windows.m4 common/autoconf/generated-configure.sh
2 files changed, 5 insertions(+), 5 deletions(-) [+]

-    # The cmd output ends with Windows line endings (CR/LF), the grep command will strip that away
-    cygwin_winpath_root=`cd / ; cmd /c cd | grep ".*"`
+    # The cmd output ends with Windows line endings (CR/LF)
+    cygwin_winpath_root=`cd / ; cmd /c cd | $TR -d '\r\n'`
```

Blocking:
- eclipse/openj9#1662
- eclipse/openj9#1778

**Comment by keithc-ca** [comment]
@AdamBrousseau If you put that change into a pull request, I can merge it for you.

**Comment by AdamBrousseau** [comment]
I'm guessing since the repo was just updated today, the change we need was not in a tagged level? I'm not familiar with how we pull updates.
@keithc-ca if we make that change ourselves, what will the process be when the actual change is pulled in? I think from a Git perspective, if we make the same exact change, then Git will just continue on.

**Comment by keithc-ca** [comment]
Yes, the same change should just merge cleanly, but I'd like to hear from @andrew-m-leonard - hopefully he can confirm and answer your questions.
