### ISSUE TITLE
openj9-notices.html is out of date

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk8#79]
The content of https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/openj9-notices.html is out of date wrt OpenJ9 https://github.com/eclipse/openj9/blob/master/longabout.html

The file is copied into the jdk and jre images when builds are created. Rather than update the copy, a better solution is to delete openj9-notices.html, and copy the OpenJ9 file to the images instead, which can be renamed to openj9-notices.html during the copy.

**Comment by pshipton** [comment]
Note this affects all versions of the extensions.

**Comment by adamfarley** [comment]
"Out of date" - I see that the date at the top of the jdk8 notices file is a month later than the date at the top of the openj9 notices file. When we consider the bits in the jdk8 file which are not in the openj9 file (like the bit near the top about Third Party Content, and the bit about libauxv), it looks like a merge would be more appropriate here. 

However, Peter initial comment appears to explicitly rule this out as an option, so perhaps he knows something I don't.

@pshipton - Thoughts?

**Comment by pshipton** [comment]
The idea is to use the original OpenJ9 file, rather than maintain a copy of it in all the extensions repos. A copy in the extensions repos is not required, the OpenJ9 file can be copied to the correct place in the images. This avoids having to update the copy any time the original file is updated. Already the copies were not updated in a timely fashion when the original changed, and it was only discovered by accident they were out of sync. It may be a little more work initially to use the original file instead of the copy, but in the longer term I believe its worth the effort.

**Comment by adamfarley** [comment]
Then do you advise we move the musl bit into the OpenJ9 file, or do without it when we copy the openJ9 file instead of the extensions notices file? I don't see a third option, unless we want to copy both files, or perform some kind of merge at build time, both of which sound fraught with complications.

**Comment by pshipton** [comment]
I don't understand the question. The OpenJ9 file https://github.com/eclipse/openj9/blob/master/longabout.html contains the musl license. This file just needs to be copied into the images (see references to openj9-notices.html in OpenJ9.gmk) and renamed to openj9-notices.html and then https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/openj9-notices.html can be deleted.

**Comment by pshipton** [comment]
libauxv is not included in OpenJ9 and was removed from the OpenJ9 longabout.html. It is used by OMR however the license was changes, see https://github.com/eclipse/omr/pull/2171

**Comment by pshipton** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/openj9-notices.html is copied by #85

**Comment by adamfarley** [comment]
So the next question is: do the extensions repositories require the notices files if they aren't used in the build? I see OpenJ9 has its own notices file independent of longabout.html.

**Comment by pshipton** [comment]
For the record I don't believe it is necessary for the extensions projects to contain a copy of the OpenJ9 notices. The copy was originally added to meet the requirement to copy the OpenJ9 notices into the JDK and JRE images, which has now been resolved by directly copying the file from the OpenJ9 source. As such, https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/openj9-notices.html , and the copy in other extension repos, can now be deleted.

**Comment by pshipton** [comment]
The obsolete notices file is removed by:
- #86 
- ibmruntimes/openj9-openjdk-jdk10#33
